version: "3"
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  admin:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - install_flags=--no-interaction --with integration --extras aca-py
    command: start --arg-file integration.yml --label admin -e http://admin:3000 --log-level info

  tests:
    container_name: juggernaut
    build:
      context: .
      dockerfile: Dockerfile.test.runner
    environment:
      - WAIT_BEFORE=3
      - WAIT_HOSTS=admin:3000
      - WAIT_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - admin
