 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/basicmessage_storage/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/basicmessage_storage"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/connection_update/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/connection_update"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/firebase_push_notifications/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/firebase_push_notifications"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/multitenant_provider/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/multitenant_provider"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/oid4vci/integration/afj_runner"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/oid4vci/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/oid4vci"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/plugin_globals/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/plugin_globals"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/redis_events/docker/services"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/redis_events/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/redis_events"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/rpc/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/rpc"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/cheqd"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/cheqd/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/connections"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/connections/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for TypeScript and JavaScript
  - package-ecosystem: "npm"
    directory: "/oid4vci/demo/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]

  # Maintain dependencies for TypeScript and JavaScript
  - package-ecosystem: "npm"
    directory: "/oid4vci/demo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]

  # Maintain dependencies for TypeScript and JavaScript
  - package-ecosystem: "npm"
    directory: "/oid4vci/integration/afj"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/basicmessage_storage/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/connection_update/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/firebase_push_notifications/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/multitenant_provider/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/oid4vci/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/plugin_globals/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/redis_events/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for dev Container
  - package-ecosystem: "devcontainers"
    directory: "/rpc/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/basicmessage_storage/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/basicmessage_storage/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/basicmessage_storage/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/connection_update/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/connection_update/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/connection_update/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/firebase_push_notifications/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/firebase_push_notifications/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/firebase_push_notifications/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/multitenant_provider/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/multitenant_provider/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/multitenant_provider/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/demo/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/integration/afj"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/integration/afj_runner"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/oid4vci/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/plugin_globals/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/plugin_globals/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/plugin_globals/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/redis_events/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/redis_events/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/redis_events/docker/services"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/redis_events/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/rpc/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/rpc/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/rpc/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/cheqd/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/cheqd/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/cheqd/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/connections/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

