version: "3"
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  bob:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - install_flags=--no-interaction --with integration --extras aca-py
    command: start --arg-file integration.yml --plugin-config plugins.yml --label bob -e http://bob:3000 --log-level info

  alice:
    image: plugin-image
    command: start --arg-file integration.yml --plugin-config plugins.yml --label alice -e http://alice:3000 --log-level info

  tests:
    container_name: juggernaut
    build:
      context: .
      dockerfile: Dockerfile.test.runner
    environment:
      - WAIT_BEFORE=3
      - WAIT_HOSTS=bob:3000, alice:3000
      - WAIT_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - bob
      - alice
