FROM python:3.12-bookworm

WORKDIR /fastapi

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv "$VIRTUAL_ENV"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN apt-get -y update
RUN apt-get -y install git

RUN pip install --upgrade pip
RUN pip install poetry
RUN git clone https://github.com/decentralized-identity/trustdidweb-server-py.git
WORKDIR /fastapi/trustdidweb-server-py/server
RUN poetry install

CMD ["python", "main.py"]