FROM python:3.12-slim-bookworm AS base

WORKDIR /usr/src

USER root

COPY demo/holder.py app/__main__.py
COPY demo/utils app/utils
COPY integration/ app/integration

RUN touch app/integration/__init__.py

COPY demo/requirements.txt /opt/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/requirements.txt

ENV PYTHONPATH="/usr/src/app"

ENTRYPOINT ["bash"]
