label: indy_ledger

admin: [0.0.0.0, 3001]
admin-insecure-mode: true
auto-provision: true

inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

wallet-type: askar

wallet-name: indy_ledger_wallet
wallet-key: indy_ledger_wallet_key

plugin:
  - indy_ledger

plugin-config: /workspaces/acapy-plugins/indy_ledger/docker/plugin_config.yml

log-level: info

auto-accept-invites: true
auto-respond-messages: true
