-- create :ADMIN_DB_USER user
CREATE ROLE :ADMIN_DB_USER
WITH
    LOGIN PASSWORD :ADMIN_DB_PASSWORD NOSUPERUSER CREATEDB CREATEROLE INHERIT NOBYPASSRLS NOREPLICATION;

-- create :ADMIN_DB_NAME database
CREATE DATABASE :ADMIN_DB_NAME OWNER :ADMIN_DB_USER ENCODING 'UTF8' TEMPLATE template0;

-- grant permissions to :ADMIN_DB_USER
GRANT CONNECT,
CREATE ON DATABASE :ADMIN_DB_NAME TO :ADMIN_DB_USER;