version: "3"
services:
  issuer:
    image: oid4vc
    build: 
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8081:8081"
    volumes:
      - ../docker/entrypoint.sh:/entrypoint.sh:ro,z
      - ../oid4vc:/usr/src/app/oid4vc:z
    environment:
      RUST_LOG: warn
      OID4VCI_HOST: 0.0.0.0
      OID4VCI_PORT: 8081
      OID4VCI_ENDPOINT: "http://issuer:8081"
    command: >
      start
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://issuer:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --emit-new-didcomm-prefix
        --wallet-name issuer
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --plugin oid4vc
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  tests:
    image: oid4vc-test-runner
    build:
      context: .
    volumes:
      - ./oid4vci_client:/usr/src/app/oid4vci_client:z
      - ./tests:/usr/src/app/tests:z
    environment:
      ISSUER_ADMIN_ENDPOINT: http://issuer:3001
    depends_on:
      issuer:
        condition: service_healthy
        
