#!/bin/bash
# Generate test certificates for walt.id mDOC testing
# These are pre-generated and committed to the repo for reproducible testing
# Regenerate if needed using: ./generate-certs.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Certificate validity: 10 years (3650 days)
VALIDITY_DAYS=3650

echo "Generating ECDSA P-256 Root CA..."

# Generate Root CA private key
openssl ecparam -name prime256v1 -genkey -noout -out root-ca.key

# Generate Root CA certificate (self-signed)
openssl req -x509 -new -nodes \
    -key root-ca.key \
    -sha256 \
    -days $VALIDITY_DAYS \
    -out root-ca.pem \
    -subj "/C=US/ST=Utah/L=Provo/O=Test Indicio mDOC CA/OU=Testing/CN=Test mDOC Root CA"

echo "Generating ECDSA P-256 Issuer Certificate..."

# Generate Issuer private key
openssl ecparam -name prime256v1 -genkey -noout -out issuer.key

# Generate Issuer CSR
openssl req -new \
    -key issuer.key \
    -out issuer.csr \
    -subj "/C=US/ST=Utah/L=Provo/O=Test Indicio mDOC Issuer/OU=Testing/CN=Test mDOC Issuer"

# Create extensions file for issuer cert
cat > issuer-ext.cnf << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = acapy-issuer.local
DNS.2 = localhost
EOF

# Sign Issuer certificate with Root CA
openssl x509 -req \
    -in issuer.csr \
    -CA root-ca.pem \
    -CAkey root-ca.key \
    -CAcreateserial \
    -out issuer.pem \
    -days $VALIDITY_DAYS \
    -sha256 \
    -extfile issuer-ext.cnf

# Create certificate chain (issuer + root)
cat issuer.pem root-ca.pem > issuer-chain.pem

# Create walt.id x509.conf format
cat > x509.conf << EOF
# X.509 Trust Configuration for walt.id wallet
# Generated by generate-certs.sh
# Root CA certificate for mDOC verification

$(cat root-ca.pem)
EOF

# Clean up temporary files
rm -f issuer.csr issuer-ext.cnf root-ca.srl

echo ""
echo "Certificates generated successfully:"
echo "  - root-ca.key     : Root CA private key (keep secure)"
echo "  - root-ca.pem     : Root CA certificate (trust anchor)"
echo "  - issuer.key      : Issuer private key (for ACA-Py)"
echo "  - issuer.pem      : Issuer certificate"
echo "  - issuer-chain.pem: Full certificate chain"
echo "  - x509.conf       : walt.id trust configuration"
echo ""
echo "Validity: $VALIDITY_DAYS days from $(date)"
