FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app

# install poetry
RUN pip3 install --no-cache-dir poetry==2.1.2

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.12.1
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# install dependencies
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --only main

# add tests to image
COPY tests/* tests/

ENTRYPOINT ["/bin/sh", "-c", "/wait && sleep 10 && poetry run pytest \"$@\"", "--"]
