label: webvh-witness

auto-provision: true

admin: [0.0.0.0, 8020]
admin-insecure-mode: true

inbound-transport:
  - [http, 0.0.0.0, 8021]
  - [ws, 0.0.0.0, 8022]
outbound-transport: http
endpoint:
  - http://localhost:8021

plugin:
  - webvh

no-ledger: true

# Wallet
wallet-type: askar-anoncreds
wallet-name: witness-wallet
wallet-key: insecure
wallet-allow-insecure-seed: true # Don't do this in production

log-level: info

auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true


# Plugin
plugin-config-value:
   - did-webvh.server_url=https://id.test-suite.app
   - did-webvh.role=witness
  #  - did-webvh.auto_attest=True
