label: connections inviter

admin: [0.0.0.0, 3001]
admin-insecure-mode: false
admin-api-key: change-me

inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://localhost:3000

no-ledger: true

plugin:
  - connections

log-level: info

auto-accept-invites: true
auto-respond-messages: true

# Wallet
auto-provision: true
wallet-type: askar
wallet-name: connections-wallet
wallet-key: insecure
